### ISSUE TITLE
Timeline fails to load after 2.3.8 update w/ Postgres

### ISSUE THREAD

**Issue by kernelkaribou** [photoview/photoview#545]
**Describe the bug**
After upgrading to 2.3.8, can no long view the timeline. Get an error:

ERROR: syntax error at or near "media" (SQLSTATE 42601)

Reviewing the docker logs:

2021/09/28 23:59:44 /app/graphql/resolvers/timeline.go:37 ERROR: syntax error at or near "media" (SQLSTATE 42601)
[1.168ms] [rows:0] SELECT "media"."id","media"."created_at","media"."updated_at","media"."title","media"."path","media"."path_hash","media"."album_id","media"."exif_id","media"."date_shot","media"."type","media"."video_metadata_id","media"."side_car_path","media"."side_car_hash" FROM "media" JOIN albums ON media.album_id = albums.id WHERE albums.id IN (SELECT user_albums.album_id FROM "user_albums" WHERE user_id = 1) ORDER BY YEAR(media.date_shot) DESC,MONTH(media.date_shot) DESC,DAY(media.date_shot) DESC,albums.title ASC,TIME(media.date_shot) DESC LIMIT 200

Looking in the logs

**To Reproduce**
1. Update docker image to 2.3.8 (using latest tag)
2. Login
3. Select Timeline

**Expected behavior**
Ability to view the timeline

**Screenshots**

**Your environment:**

 - Are you using Docker? yes
 - Database: postgres 13
 - Browser: Microsoft Edge

**Additional context**
Reverting back to 2.3.6 corrected the issue. Attempting to run the query shown in the error log in PgAdmin gave me the following error:

ERROR:  syntax error at or near "MEDIA"
LINE 21:  TIME(MEDIA.DATE_SHOT) DESC
               ^
SQL state: 42601
Character: 549

Modifying the query to simply order by Date_Shot DESC addressed the syntax error in PgAdmin

SELECT "media"."id",
	"media"."created_at",
	"media"."updated_at",
	"media"."title",
	"media"."path",
	"media"."path_hash",
	"media"."album_id",
	"media"."exif_id",
	"media"."date_shot",
	"media"."type",
	"media"."video_metadata_id",
	"media"."side_car_path",
	"media"."side_car_hash"
FROM "media"
JOIN ALBUMS ON MEDIA.ALBUM_ID = ALBUMS.ID
WHERE ALBUMS.ID IN
		(SELECT USER_ALBUMS.ALBUM_ID
			FROM "user_albums"
			WHERE USER_ID = 1)
ORDER BY MEDIA.DATE_SHOT DESC
LIMIT 200

![image](https://user-images.githubusercontent.com/25406580/135182725-d3999416-aec4-4cf6-b9d0-9b54fef4c4e8.png)

**Comment by viktorstrate** [comment]
Already fixed, duplicate of #536
